kind: ReplicaSet
apiVersion: apps/v1
metadata:
   name: nginx
  #these lables are replicaset labels
labels:
   app: frontend
   tier: web
spec:
# modify replicas according to our case
   replicas: 3
   selector: 
   # replicaset use these labels to find the pods for creating desired number of replicas
     match Labels:
       app: frontend
       tier: web
   # pod template
    
     template:
       metadata:
         Labels:
         app: frontend
         tier: web
     spec:
      containers:
      - name: nginx
        image: nginx
