apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx
  # lables of deployment resources
   labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec:

   replicas: 3
   selector: 
   
     matchLabels:
       app: nginx
       tier: frontend
       purpose: deployment
   # pod template
    
   template:
     metadata:
       labels:
         app: nginx
         tier: frontend
         purpose: deployment
     spec:
       containers:
       - name: nginx
         image: name:latest
         ports:
         - containerPort: 80
